[package]
name = "mptree"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]
description = "An mp3 decoder library written in pure Rust."

[dependencies]
byteorder = "1.3.1"
bitstream-io = "0.8.2"
crc16 = "0.3.3"
